# ref: https://github.com/yccyenchicheng/AutoSDF, https://github.com/CompVis/latent-diffusion/
# code/configs/pvqvae_nembed-8192-z-3x16x16x16-snet.yaml

model:
  params:
    embed_dim: 3
    n_embed: 8192
    ddconfig:
      double_z: False
      z_channels: 3
      resolution: 64
      in_channels: 1
      out_ch: 1
      ch: 64
      # ch_mult: [1,1,2,2,4]  # num_down = len(ch_mult)-1
      ch_mult: [1,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 1
      attn_resolutions: []
      dropout: 0.0

lossconfig:
  params:
    codebook_weight: 1.0